import { HomeIcon } from "@heroicons/react/24/solid";
import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import About from "../components/About";
import ContactMe from "../components/ContactMe";
import Experience from "../components/Experience";
import Header from "../components/Header";
import Hero from "../components/Hero";
import Projects from "../components/Projects";
import Skills from "../components/Skills";

const Home: NextPage = () => {
  let date = new Date();
  let year = date.getFullYear();
  return (
    <div className="bg-[rgb(36,36,36)] text-white h-screen snap-y snap-mandatory overflow-y-scroll overflow-x-hidden z-0 md:scrollbar md:scrollbar-track-gray-400/20 md:scrollbar-thumb-[#F7AB0A]/80">
      <Head>
        <title>Portfolio || Mehdi Aniq Filali</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* Header */}
      <Header />

      {/* Hero */}
      <section id="hero" className="snap-start">
        <Hero />
      </section>

      {/* About */}
      <section id="about" className="snap-center">
        <About />
      </section>

      {/* Experience */}
      <section id="experience" className="snap-center">
        <Experience />
      </section>

      {/* Skills */}
      <section id="skills" className="snap-start">
        <Skills />
      </section>

      {/* Projects */}
      <section id="projects" className="snap-start">
        <Projects />
      </section>

      {/* Contact Me */}
      <section id="contact" className="snap-start">
        <ContactMe />
      </section>

      {/* footer */}
      <Link href="#hero">
        <footer className="sticky bottom-20 md:bottom-5 w-full cursor-pointer">
          <div className="flex items-center justify-center">
            <p className="hidden md:block md:absolute md:text-xs text-gray-500 md:left-8 xl:left-72">
              {"© " + year + ", Mehdi Aniq-Filali | Tous droits réservés"}
            </p>
            <HomeIcon className="text-[#F7AB0A] h-10 w-10 animate-pulse border border-[#F7AB0A] p-1 rounded-full" />
          </div>
        </footer>
      </Link>
    </div>
  );
};

export default Home;
